(define (one-half xs) 
  (cond ((<= (count xs) 1) xs) 
        (else (se (first xs) 
                  (one-half (bf (bf xs)))))))

(define (other-half xs) 
  (cond ((<= (count xs) 1) 
         ()) 
        (else (se (first (bf xs)) 
                  (other-half (bf (bf xs)))))))

(define (merge xs ys) 
  (cond ((empty? xs) ys) 
        ((empty? ys) xs) 
        ((before? (first xs) 
                  (first ys)) 
         (se (first xs) 
             (merge (bf xs) ys))) 
        (else (se (first ys) 
                  (merge xs (bf ys))))))

(define (mergesort xs) 
  (cond ((<= (count xs) 1) xs) 
        (else (merge (mergesort (one-half xs)) 
                     (mergesort (other-half xs))))))

